language: cpp
compiler: clang
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

          packages:
            - build-essential
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    
before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz
  - tar -xf cmake-3.12.1-Linux-x86_64.tar.xz
  - export PATH=$PATH:cmake-3.12.1-Linux-x86_64/bin
