language: cpp
compiler: clang
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - clang-4.0
            - cmake
            - cmake-data
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    
before_install:
  - eval "${MATRIX_EVAL}"

script:
