language: cpp
compiler: clang
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    
before_install:
  - eval "${MATRIX_EVAL}"
  - curl https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh | bash
