language: cpp
compiler: clang
env:
  global:
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

          packages:
            - build-essential
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - opt -load lib/libTestPass.so -test-pass -analyze ../tests/test1.ll
  - opt -load lib/libTestPass.so -test-pass -analyze ../tests/test2.ll
  - opt -load lib/libTestPass.so -test-pass -analyze ../tests/test3.ll
  - opt -load lib/libTestPass.so -test-pass -analyze ../tests/test4.ll
  - opt -load lib/libTestPass.so -test-pass -analyze ../tests/test5.ll
  - opt -load lib/libTestPass.so -test-pass -analyze ../tests/test6.ll
  - opt -load lib/libTestPass.so -test-pass -analyze ../tests/test7.ll

before_install:
  - eval "${MATRIX_EVAL}"